---
title: "Workflow"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Workflow}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
devtools::load_all()
script_path <- system.file("vignette_helpers", "db_functions.R", package = "curveRfreq")
if (file.exists(script_path)) {
  source(script_path)
} else {
  warning("Script file not found at expected path: ", script_path)
}
conn <- get_db_connection()
param_user = "seamus.owen.stein@dartmouth.edu"

```

```{r configuration}
# other packages for loading
library(glue)
verbose = TRUE
# models to be considered in the algorithm. If one is not included, it is not considered in the model candidates.
model_names = c("logistic5", "loglogistic5", "logistic4", "loglogistic4", "gompertz4") 
param_group = "standard_curve_options"
is_display_log_response = TRUE
is_display_log_independent = TRUE

project_id = 17
study_accession = "MADI_01"
experiment_accession ="IgG1"
feature = "IgG1"
# plate = "plate_3"
# nominal_sample_dilution <- "1000"

## controls next to figure
source = "Standard"
antigen = "victoria"
plate_nom = "plate_3-1000"

```

```{r, load data}



loaded_data <- pull_data(study_accession = study_accession, experiment_accession = experiment_accession, project_id = project_id, conn = conn)
#nominal_sample_dilution = unique(loaded_data$standards$nominal_sample_dilution)[1]
```

```{r, response and independent variables}
response_var <- loaded_data$response_var
indep_var <- loaded_data$indep_var
cat("response variable:", response_var, "\n")
cat("independent variable:", indep_var)
```

```{r, antigen constraints}
antigen_constraints <- loaded_data$antigen_constraints
antigen_constraints <- antigen_constraints[antigen_constraints$antigen == antigen,]
print(antigen_constraints)
```
```{r, study parameters}
study_params <- fetch_study_parameters(study_accession=study_accession, param_user=param_user, param_group=param_group,
                                       project_id = project_id, conn)
print(study_params)
```


```{r}
# # Build curve_id in configuration
# curve_id_selected <- paste(
#   project_id, study_accession, experiment_accession,
#   feature, source, antigen,
#   plate, nominal_sample_dilution,
#   sep = "|"
# )
# 
# # One-line filter
# antigen_plate <- select_antigen_plate(
#   loaded_data         = loaded_data,
#   curve_id            = curve_id_selected,
#   antigen_constraints = loaded_data$antigen_constraints,
#   verbose             = TRUE
# )
```

```{r, select antigen on the plate}
antigen_plate <-  select_antigen_plate(
        loaded_data          = loaded_data,
        study_accession      = study_accession,
        experiment_accession = experiment_accession,
        source               = source,
        antigen              = antigen,
        plate                = plate_nom,
        antigen_constraints  = antigen_constraints
      )

# antigen_plate$plate_standard
```

```{r, preproccess data}
preprocessed_data <- preprocess_robust_curves(data = antigen_plate$plate_standard, antigen_settings = antigen_plate$antigen_settings,
                                     response_variable = response_var,
                                     independent_variable = indep_var,
                                     is_log_response = study_params$is_log_response,
                                     blank_data = antigen_plate$plate_blanks,
                                     blank_option = study_params$blank_option,
                                     is_log_independent = study_params$is_log_independent,
                                     apply_prozone = study_params$applyProzone,
                                     verbose = verbose)
preprocessed_data$data
preprocessed_data$antigen_fit_options
```

```{r, model formulas}
formulas <- select_model_formulas(fixed_constraint = antigen_plate$fixed_a_result, response_variable = response_var,
                                    is_log_response = study_params$is_log_response, model_names = model_names)
print(formulas)
```

```{r, model constraints}
model_constraints <- obtain_model_constraints(data = preprocessed_data$data,
                                                formulas = formulas,
                                                independent_variable = indep_var,
                                                response_variable = response_var,
                                                is_log_response = study_params$is_log_response,
                                                is_log_concentration = study_params$is_log_independent,
                                                antigen_settings = antigen_plate$antigen_settings,
                                                max_response = max(preprocessed_data$data[[response_var]], na.rm = TRUE),
                                                min_response = min(preprocessed_data$data[[response_var]], na.rm = TRUE),
                                                verbose = verbose
                                                )
model_constraints
```


```{r, starting lists}
start_lists <- make_start_lists(model_constraints = model_constraints,
                                  frac_generate = 0.8,
                                  quants = c(low = 0.2, mid = 0.5, high = 0.8))
```


```{r, compute robust curves}
fit_robust_lm <- compute_robust_curves(prepped_data = preprocessed_data$data,
                                         response_variable = response_var,
                                         independent_variable = indep_var,
                                         formulas = formulas,
                                         model_constraints = model_constraints,
                                         start_lists = start_lists,
                                         verbose = verbose)
```


```{r, summary of fits}
fit_summary <- summarize_model_fits(fit_robust_lm, verbose = verbose)
fit_summary
```
```{r}
fit_params <- summarize_model_parameters(models_fit_list = fit_robust_lm, level = 0.95, model_names = model_names)
```

```{r}
plot_data <- get_plot_data(models_fit_list = fit_robust_lm,
                             prepped_data = preprocessed_data$data,
                             fit_params = fit_params,
                             fixed_a_result = antigen_plate$fixed_a_result,
                             model_names = model_names,
                             x_var = indep_var,
                             y_var = response_var)
```

```{r, model comparisions, fig.width = 10, fig.height = 12}
plot_model_comparisons(plot_data = plot_data,
                         model_names = model_names,
                         x_var = indep_var,
                         y_var = response_var,
                         use_patchwork = TRUE)
```

```{r}
best_fit <- select_model_fit_AIC(fit_summary = fit_summary,
                                   fit_robust_lm = fit_robust_lm,
                                   fit_params = fit_params,
                                   plot_data = plot_data,
                                   verbose = verbose)

best_fit
```


```{r}
## add the tidy to the best fit object
best_fit <- tidy.nlsLM(best_fit = best_fit, fixed_a_result = antigen_plate$fixed_a_result, model_constraints =
               model_constraints, antigen_settings = antigen_plate$antigen_settings,
               antigen_fit_options = prepped_data$antigen_fit_options, verbose = verbose)

best_fit$best_tidy
```

```{r}
se_antigen_table <- compute_antigen_se_table(
      standards_data = loaded_data$standards,
      response_col   = response_var,
      dilution_col   = "dilution",
      plate_col      = "plate",
      grouping_cols  = c("project_id", "study_accession", "experiment_accession", 
                         "source_nom", "antigen", "feature"),
      verbose        = TRUE
    )

se_antigen_table
```

```{r}
current_se <-  lookup_antigen_se(
        se_table             = se_antigen_table,
        study_accession      = study_accession,
        experiment_accession = experiment_accession,
        source = source,
        antigen = antigen,
        feature = unique(best_fit$best_data$feature)
      )

current_se

```


```{r}
best_fit <- predict_and_propagate_error(
        best_fit        = best_fit,
        response_var    = response_var,
        antigen_plate   = antigen_plate,
        study_params    = study_params,
        se_std_response = current_se,
        verbose         = verbose
      )


print(head(best_fit$sample_se))
```

```{r, fig.width=14, fig.height= 8, out.width="100%"}
plot_standard_curve(best_fit = best_fit, is_display_log_independent = is_display_log_independent,
                    is_display_log_response = is_display_log_response,
                    pcov_threshold = 15,
                    study_params = study_params,
                    response_variable = response_var,
                    independent_variable = indep_var)
```
 
